slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: HuberLoss

    # ROS Parameters
    use_sim_time: True
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    use_map_saver: true
    mode: mapping

    # Debug and performance settings - TỐI ƯU CHO TỐC ĐỘ THẤP
    debug_logging: false
    throttle_scans: 1  # Giữ mọi scan do tốc độ thấp
    transform_publish_period: 0.02  # Tăng tần suất publish cho chuyển động mượt
    map_update_interval: 1.0  # Cập nhật map thường xuyên hơn
    resolution: 0.05  # Độ phân giải map 5cm
    min_laser_range: 0.12  # Giảm xuống 15cm cho môi trường trong nhà
    max_laser_range: 10.0  # Giới hạn 10m cho độ tin cậy cao
    minimum_time_interval: 0.1  # Giảm để xử lý scan thường xuyên hơn
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: false
    message_queue_size: 20  # Tăng lên cho buffer tốt hơn

    # General Parameters - TỐI ƯU CHO ROBOT CHẬM
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.02  # GIẢM xuống 2cm cho robot chậm
    minimum_travel_heading: 0.02  # GIẢM xuống ~1.15° cho nhạy với xoay nhỏ
    scan_buffer_size: 30  # Tăng buffer cho nhiều scan history
    scan_buffer_maximum_scan_distance: 10.0  
    link_match_minimum_response_fine: 0.2  # Cân bằng giữa độ tin cậy và flexibility
    link_scan_maximum_distance: 6.0  # Giảm cho môi trường trong nhà
    loop_search_maximum_distance: 4.0  # Giảm cho không gian nhỏ
    do_loop_closing: true 
    loop_match_minimum_chain_size: 5  # Giảm để phát hiện loop nhanh hơn
    loop_match_maximum_variance_coarse: 1.5  # Chặt chẽ hơn cho loop closure
    loop_match_minimum_response_coarse: 0.5  
    loop_match_minimum_response_fine: 0.6  # Tăng độ tin cậy
    wait_for_transform: true
    wait_time: 0.5  # Giảm thời gian chờ

    # Correlation Parameters - TỐI ƯU CHO CHUYỂN ĐỘNG CHẬM
    correlation_search_space_dimension: 0.4  # Giảm do tốc độ thấp, drift ít
    correlation_search_space_resolution: 0.005  # Tăng độ phân giải
    correlation_search_space_smear_deviation: 0.02  # Giảm cho độ chính xác cao

    # Loop Closure Parameters - QUAN TRỌNG CHO MAPPING TỐT
    loop_search_space_dimension: 6.0  # Phù hợp cho không gian vừa
    loop_search_space_resolution: 0.02  # Độ phân giải tốt
    loop_search_space_smear_deviation: 0.015  # Chính xác hơn

    # Scan Matcher Parameters - TINH CHỈNH CHO ROBOT 35RPM
    distance_variance_penalty: 0.5  # Cân bằng khoảng cách
    angle_variance_penalty: 1.0  # Cân bằng góc  
    fine_search_angle_offset: 0.00087  # ~0.05° - rất chính xác
    coarse_search_angle_offset: 0.15  # ~8.6° - phù hợp tốc độ xoay
    coarse_angle_resolution: 0.0175  # ~1° resolution
    minimum_angle_penalty: 0.8  # Nghiêm ngặt với góc
    minimum_distance_penalty: 0.4  # Linh hoạt với khoảng cách
    use_response_expansion: true